#pragma once

enum class eResMaterial
{
	Boss Stage(Gargoyles)_child_0_0,
	Boss Stage(Gargoyles)_child_10_0,
	Boss Stage(Gargoyles)_child_11_0,
	Boss Stage(Gargoyles)_child_12_0,
	Boss Stage(Gargoyles)_child_13_0,
	Boss Stage(Gargoyles)_child_14_0,
	Boss Stage(Gargoyles)_child_15_0,
	Boss Stage(Gargoyles)_child_16_0,
	Boss Stage(Gargoyles)_child_17_0,
	Boss Stage(Gargoyles)_child_18_0,
	Boss Stage(Gargoyles)_child_19_0,
	Boss Stage(Gargoyles)_child_1_0,
	Boss Stage(Gargoyles)_child_20_0,
	Boss Stage(Gargoyles)_child_21_0,
	Boss Stage(Gargoyles)_child_22_0,
	Boss Stage(Gargoyles)_child_23_0,
	Boss Stage(Gargoyles)_child_24_0,
	Boss Stage(Gargoyles)_child_25_0,
	Boss Stage(Gargoyles)_child_26_0,
	Boss Stage(Gargoyles)_child_27_0,
	Boss Stage(Gargoyles)_child_28_0,
	Boss Stage(Gargoyles)_child_29_0,
	Boss Stage(Gargoyles)_child_2_0,
	Boss Stage(Gargoyles)_child_30_0,
	Boss Stage(Gargoyles)_child_31_0,
	Boss Stage(Gargoyles)_child_32_0,
	Boss Stage(Gargoyles)_child_33_0,
	Boss Stage(Gargoyles)_child_34_0,
	Boss Stage(Gargoyles)_child_35_0,
	Boss Stage(Gargoyles)_child_3_0,
	Boss Stage(Gargoyles)_child_4_0,
	Boss Stage(Gargoyles)_child_5_0,
	Boss Stage(Gargoyles)_child_6_0,
	Boss Stage(Gargoyles)_child_7_0,
	Boss Stage(Gargoyles)_child_8_0,
	Boss Stage(Gargoyles)_child_9_0,
	Capsule_child_0_0,
	Cube_child_0_0,
	gargoyles_child_0_0,
	gargoyles_child_10_0,
	gargoyles_child_11_0,
	gargoyles_child_12_0,
	gargoyles_child_13_0,
	gargoyles_child_14_0,
	gargoyles_child_15_0,
	gargoyles_child_16_0,
	gargoyles_child_17_0,
	gargoyles_child_18_0,
	gargoyles_child_19_0,
	gargoyles_child_1_0,
	gargoyles_child_20_0,
	gargoyles_child_2_0,
	gargoyles_child_3_0,
	gargoyles_child_4_0,
	gargoyles_child_5_0,
	gargoyles_child_6_0,
	gargoyles_child_7_0,
	gargoyles_child_8_0,
	gargoyles_child_9_0,
	Iron_Golem3_child_0_0,
	Iron_Golem3_child_1_0,
	Iron_Golem3_child_2_0,
	Plane_child_0_0,
	Quad_child_0_0,
	Sphere_child_0_0,
	Taurus_Demon_Fianl_child_0_0,
	Taurus_Demon_Fianl_child_1_0,
	Taurus_Demon_Fianl_child_2_0,
	Taurus_Demon_Fianl_child_3_0,
	Taurus_Demon_Fianl_child_4_0,
	Taurus_Demon_Fianl_child_5_0,
	Taurus_Demon_Fianl_child_6_0,
	Taurus_Demon_Fianl_child_7_0,
	Taurus_Demon_Fianl_child_8_0,
	End
};

const wchar_t* EnumResourcePath(eResMaterial type);

