#include "pch.h"
#include "EnumResourceTypeFbx.h"

static constexpr const wchar_t* eResFbxPath[static_cast<UINT>(eResFbx::End)]
{
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Diff.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Norm.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Spec.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse02_Norm.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse03_Diff.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse03_Spec.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_SP_KGW.tga",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274_s.dds",
	L"\\Fbx\\SOUL\\Artorias.FBX",
	L"\\Fbx\\SOUL\\Artorias4.FBX",
	L"\\Fbx\\SOUL\\Player_Artorias.FBX",
	L"\\Fbx\\Twilighr.fbm\\TwilightNormalSkin_Twilight_BaseColor.png",
	L"\\Fbx\\unitychan.fbm\\body_01.tga",
	L"\\Fbx\\unitychan.fbm\\cheek_00.tga",
	L"\\Fbx\\unitychan.fbm\\eyeline_00.tga",
	L"\\Fbx\\unitychan.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\unitychan.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\unitychan.fbm\\face_00.tga",
	L"\\Fbx\\unitychan.fbm\\hair_01.tga",
	L"\\Fbx\\unitychan.fbm\\skin_01.tga",
	L"\\Fbx\\unitychan2.fbm\\body_01.tga",
	L"\\Fbx\\unitychan2.fbm\\cheek_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eyeline_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\unitychan2.fbm\\face_00.tga",
	L"\\Fbx\\unitychan2.fbm\\hair_01.tga",
	L"\\Fbx\\unitychan2.fbm\\skin_01.tga",
	L"\\Fbx\\black.fbx",
	L"\\Fbx\\c7100.fbx",
	L"\\Fbx\\c9990.fbx",
	L"\\Fbx\\coba.fbx",
	L"\\Fbx\\Dragon.fbx",
	L"\\Fbx\\hero.fbx",
	L"\\Fbx\\hero2.fbx",
	L"\\Fbx\\house.fbx",
	L"\\Fbx\\monster.fbx",
	L"\\Fbx\\night.fbx",
	L"\\Fbx\\Room.fbx",
	L"\\Fbx\\sphere.fbx",
	L"\\Fbx\\Spider.fbx",
	L"\\Fbx\\Spider_2.fbx",
	L"\\Fbx\\Spider_3.fbx",
	L"\\Fbx\\Twilighr.fbx",
	L"\\Fbx\\Twilight_Walk.FBX",
	L"\\Fbx\\unitychan.fbx",
	L"\\Fbx\\unitychan2.fbx",
};

const wchar_t* EnumResourcePath(eResFbx type)
{
	return eResFbxPath[static_cast<UINT>(type)];
}

