#include "pch.h"
#include "EnumResourceTypeFbx.h"

static constexpr const wchar_t* eResFbxPath[static_cast<UINT>(eResFbx::End)]
{
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Diff.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Norm.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse01_Spec.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse02_Norm.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse03_Diff.tga",
	L"\\Fbx\\house.fbm\\SPR_Vill_Warehouse03_Spec.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_D_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_N_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_SP_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_D_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_N_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_SP_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_D_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_N_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_SP_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_D_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_N_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_SP_KGW.tga",
	L"\\Fbx\\Monster\\Monster.fbx",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Lower_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Shoulder_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_A01_Upper_SP_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_D_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_N_KGW.tga",
	L"\\Fbx\\monster.fbm\\CH_NPC_MOB_Anashar_Weapon_A01_SP_KGW.tga",
	L"\\Fbx\\painting.fbm\\c2400_AM_M_9430.dds",
	L"\\Fbx\\painting.fbm\\c2400_AM_M_9430_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_AM_M_9430_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_1.dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_1_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_1_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_2.dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_2_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_BD_M_9430_2_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_HD_M_9430.dds",
	L"\\Fbx\\painting.fbm\\c2400_HD_M_9430_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_HD_M_9430_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_LG_M_9430.dds",
	L"\\Fbx\\painting.fbm\\c2400_LG_M_9430_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_LG_M_9430_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_0406.dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_0406_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_0406_s.dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_1501.dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_1501_n [Unknown24].dds",
	L"\\Fbx\\painting.fbm\\c2400_WP_A_1501_s.dds",
	L"\\Fbx\\Shape\\Capsule.fbx",
	L"\\Fbx\\Shape\\Cube.fbx",
	L"\\Fbx\\Shape\\Free_Forest.fbx",
	L"\\Fbx\\Shape\\Plane.fbx",
	L"\\Fbx\\Shape\\Quad.fbx",
	L"\\Fbx\\Shape\\Sphere.fbx",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_AM_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_1_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_BD_A_9700_2_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_HD_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_LG_M_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274.dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Artorias4.fbm\\c4100_WP_A_0274_s.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_s.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0202.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0202_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0202_s.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0300.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0300_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_0300_s.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_1528.dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_1528_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Balder_Knight.fbm\\c2560_WP_A_1528_s.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320_s.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320_WP_A_0508.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320_WP_A_0508_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.fbm\\c2320_WP_A_0508_s.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_body.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_body_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_body_s.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_fur.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_fur_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.fbm\\c2250_fur_s.dds",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\gargoyles.fbx",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Iron_Golem3.FBX",
	L"\\Fbx\\SOUL\\Charactor\\Boss\\Taurus_Demon_Fianl.FBX",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320.dds",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320_s.dds",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320_WP_A_0508.dds",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320_WP_A_0508_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Iron_Golem3.fbm\\c2320_WP_A_0508_s.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_buttress_roof2.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_catwalk.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_floor_02.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_floor_02_s.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_glass_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_glass_01_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_glass_01_s.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_relief_03.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_chapel_wall_02.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_01_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_02.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_02_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_03.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_03_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_04.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_04_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_05.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_05_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_07.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_07_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_09.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_09_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_10.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_11.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_11_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_12.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_12_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_14.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_15.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_16.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_16_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_17.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_distant_view_17_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_06.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_06_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_08.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_08_s.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_09.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_floor_stone_09_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_gold.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_gold_s.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_handrail_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_handrail_01_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_roof_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_stair_2_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_block_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_relief_05.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_relief_05_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_relief_06.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_relief_06_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_stone_09.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_stone_09_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_01.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch2.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch2_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch3.dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch3_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).fbm\\m15_wall_white_ditch_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\map\\Boss Stage(Gargoyles).FBX",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_AM_A_9700.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_AM_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_AM_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_1.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_1_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_1_s.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_2.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_2_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_BD_A_9700_2_s.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_HD_A_9700.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_HD_A_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_HD_A_9700_s.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_LG_M_9700.dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_LG_M_9700_n [Unknown24].dds",
	L"\\Fbx\\SOUL\\Player_Artorias.fbm\\c4100_LG_M_9700_s.dds",
	L"\\Fbx\\SOUL\\Artorias.FBX",
	L"\\Fbx\\SOUL\\Artorias4.FBX",
	L"\\Fbx\\SOUL\\Balder_Knight.FBX",
	L"\\Fbx\\SOUL\\Iron_Golem.fbx",
	L"\\Fbx\\SOUL\\Iron_Golem2.FBX",
	L"\\Fbx\\SOUL\\Iron_Golem3.FBX",
	L"\\Fbx\\SOUL\\Player_Artorias.FBX",
	L"\\Fbx\\test_uc\\unitychan.fbm\\body_01.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\cheek_00.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\eyeline_00.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\face_00.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\hair_01.tga",
	L"\\Fbx\\test_uc\\unitychan.fbm\\skin_01.tga",
	L"\\Fbx\\test_uc\\unitychan.fbx",
	L"\\Fbx\\Twilighr.fbm\\TwilightNormalSkin_Twilight_BaseColor.png",
	L"\\Fbx\\uc\\uc.fbm\\body_01.tga",
	L"\\Fbx\\uc\\uc.fbm\\cheek_00.tga",
	L"\\Fbx\\uc\\uc.fbm\\eyeline_00.tga",
	L"\\Fbx\\uc\\uc.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\uc\\uc.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\uc\\uc.fbm\\face_00.tga",
	L"\\Fbx\\uc\\uc.fbm\\hair_01.tga",
	L"\\Fbx\\uc\\uc.fbm\\skin_01.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\body_01.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\cheek_00.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\eyeline_00.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\face_00.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\hair_01.tga",
	L"\\Fbx\\uc\\unitychan.fbm\\skin_01.tga",
	L"\\Fbx\\uc\\uc.fbx",
	L"\\Fbx\\unitychan.fbm\\body_01.tga",
	L"\\Fbx\\unitychan.fbm\\cheek_00.tga",
	L"\\Fbx\\unitychan.fbm\\eyeline_00.tga",
	L"\\Fbx\\unitychan.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\unitychan.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\unitychan.fbm\\face_00.tga",
	L"\\Fbx\\unitychan.fbm\\hair_01.tga",
	L"\\Fbx\\unitychan.fbm\\skin_01.tga",
	L"\\Fbx\\unitychan2.fbm\\body_01.tga",
	L"\\Fbx\\unitychan2.fbm\\cheek_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eyeline_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eye_iris_L_00.tga",
	L"\\Fbx\\unitychan2.fbm\\eye_iris_R_00.tga",
	L"\\Fbx\\unitychan2.fbm\\face_00.tga",
	L"\\Fbx\\unitychan2.fbm\\hair_01.tga",
	L"\\Fbx\\unitychan2.fbm\\skin_01.tga",
	L"\\Fbx\\unity_fbx\\Banana Man.fbm\\Banana Man Albedo.png",
	L"\\Fbx\\unity_fbx\\Free_Forest.fbm\\PP_Color_Palette.png",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Body_Albedo.tga",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Body_Normals.tga",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Cloth_Down_Albedo_01.tga",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Cloth_Down_Normals.tga",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Cloth_Up_Albedo_01.tga",
	L"\\Fbx\\unity_fbx\\Man_04.fbm\\Man_Cloth_Up_Normals.tga",
	L"\\Fbx\\unity_fbx\\PP_Tree_10.fbm\\PP_Color_Palette.png",
	L"\\Fbx\\unity_fbx\\Banana Man.fbx",
	L"\\Fbx\\unity_fbx\\Free_Forest.fbx",
	L"\\Fbx\\unity_fbx\\Man_04.fbx",
	L"\\Fbx\\unity_fbx\\PP_Tree_10.fbx",
	L"\\Fbx\\unity_fbx\\unitychan.fbx",
	L"\\Fbx\\unity_fbx\\unitychan_RUN00_F.fbx",
	L"\\Fbx\\unity_fbx\\untitled2.fbx",
	L"\\Fbx\\black.fbx",
	L"\\Fbx\\c7100.fbx",
	L"\\Fbx\\c9990.fbx",
	L"\\Fbx\\coba.fbx",
	L"\\Fbx\\Dragon.fbx",
	L"\\Fbx\\hero.fbx",
	L"\\Fbx\\hero2.fbx",
	L"\\Fbx\\house.fbx",
	L"\\Fbx\\monster.fbx",
	L"\\Fbx\\night.fbx",
	L"\\Fbx\\painting.fbx",
	L"\\Fbx\\Room.fbx",
	L"\\Fbx\\sphere.fbx",
	L"\\Fbx\\Spider.fbx",
	L"\\Fbx\\Spider_2.fbx",
	L"\\Fbx\\Spider_3.fbx",
	L"\\Fbx\\Twilighr.fbx",
	L"\\Fbx\\Twilight_Walk.FBX",
	L"\\Fbx\\unitychan.fbx",
	L"\\Fbx\\unitychan2.fbx",
};

const wchar_t* EnumResourcePath(eResFbx type)
{
	return eResFbxPath[static_cast<UINT>(type)];
}

