#pragma once

enum class eResMesh
{
	Boss Stage(Gargoyles)_child_0,
	Boss Stage(Gargoyles)_child_1,
	Boss Stage(Gargoyles)_child_10,
	Boss Stage(Gargoyles)_child_11,
	Boss Stage(Gargoyles)_child_12,
	Boss Stage(Gargoyles)_child_13,
	Boss Stage(Gargoyles)_child_14,
	Boss Stage(Gargoyles)_child_15,
	Boss Stage(Gargoyles)_child_16,
	Boss Stage(Gargoyles)_child_17,
	Boss Stage(Gargoyles)_child_18,
	Boss Stage(Gargoyles)_child_19,
	Boss Stage(Gargoyles)_child_2,
	Boss Stage(Gargoyles)_child_20,
	Boss Stage(Gargoyles)_child_21,
	Boss Stage(Gargoyles)_child_22,
	Boss Stage(Gargoyles)_child_23,
	Boss Stage(Gargoyles)_child_24,
	Boss Stage(Gargoyles)_child_25,
	Boss Stage(Gargoyles)_child_26,
	Boss Stage(Gargoyles)_child_27,
	Boss Stage(Gargoyles)_child_28,
	Boss Stage(Gargoyles)_child_29,
	Boss Stage(Gargoyles)_child_3,
	Boss Stage(Gargoyles)_child_30,
	Boss Stage(Gargoyles)_child_31,
	Boss Stage(Gargoyles)_child_32,
	Boss Stage(Gargoyles)_child_33,
	Boss Stage(Gargoyles)_child_34,
	Boss Stage(Gargoyles)_child_35,
	Boss Stage(Gargoyles)_child_4,
	Boss Stage(Gargoyles)_child_5,
	Boss Stage(Gargoyles)_child_6,
	Boss Stage(Gargoyles)_child_7,
	Boss Stage(Gargoyles)_child_8,
	Boss Stage(Gargoyles)_child_9,
	Capsule_child_0,
	Cube_child_0,
	gargoyles_child_0,
	gargoyles_child_1,
	gargoyles_child_10,
	gargoyles_child_11,
	gargoyles_child_12,
	gargoyles_child_13,
	gargoyles_child_14,
	gargoyles_child_15,
	gargoyles_child_16,
	gargoyles_child_17,
	gargoyles_child_18,
	gargoyles_child_19,
	gargoyles_child_2,
	gargoyles_child_20,
	gargoyles_child_3,
	gargoyles_child_4,
	gargoyles_child_5,
	gargoyles_child_6,
	gargoyles_child_7,
	gargoyles_child_8,
	gargoyles_child_9,
	Iron_Golem3_child_0,
	Iron_Golem3_child_1,
	Iron_Golem3_child_2,
	Plane_child_0,
	Quad_child_0,
	Sphere_child_0,
	Taurus_Demon_Fianl_child_0,
	Taurus_Demon_Fianl_child_1,
	Taurus_Demon_Fianl_child_2,
	Taurus_Demon_Fianl_child_3,
	Taurus_Demon_Fianl_child_4,
	Taurus_Demon_Fianl_child_5,
	Taurus_Demon_Fianl_child_6,
	Taurus_Demon_Fianl_child_7,
	Taurus_Demon_Fianl_child_8,
	End
};

const wchar_t* EnumResourcePath(eResMesh type);

